"""create initial2 table

Revision ID: f11aa05dc0ef
Revises: 47a567db3674
Create Date: 2024-12-04 11:18:00.625131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f11aa05dc0ef'
down_revision: Union[str, None] = '47a567db3674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('todos', 'description',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'description',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               nullable=True)
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
